version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: taskmate-db
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER        
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD 
      POSTGRES_DB: taskmate_db            
    volumes:
      - taskmate_db_data:/var/lib/postgresql/data  # Persist database data on the host machine
    ports:
      - "5432:5432"  
    networks:
      - taskmate-network

volumes:
  taskmate_db_data:   # Named volume for PostgreSQL data persistence
    driver: local

networks:
  taskmate-network:
    driver: bridge
